<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="IZDT-211" name="com.r1v2.reporting.test.HomePageScenario" tests="9" failures="1" timestamp="10 Jul 2018 12:01:30 GMT" time="12.294" errors="0">
  <testcase name="testSC_1" time="1.190" classname="com.r1v2.reporting.test.HomePageScenario"/>
  <testcase name="testSC_2" time="1.452" classname="com.r1v2.reporting.test.HomePageScenario"/>
  <testcase name="testSC_3" time="0.750" classname="com.r1v2.reporting.test.HomePageScenario"/>
  <testcase name="testSC_4" time="0.809" classname="com.r1v2.reporting.test.HomePageScenario"/>
  <testcase name="testSC_5" time="0.690" classname="com.r1v2.reporting.test.HomePageScenario"/>
  <testcase name="testSC_6" time="0.676" classname="com.r1v2.reporting.test.HomePageScenario"/>
  <testcase name="testSC_7" time="0.715" classname="com.r1v2.reporting.test.HomePageScenario"/>
  <testcase name="testSC_8" time="0.101" classname="com.r1v2.reporting.test.HomePageScenario"/>
  <testcase name="testSC_9" time="5.911" classname="com.r1v2.reporting.test.HomePageScenario">
    <failure type="java.lang.AssertionError" message=" Login Page is not displayed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError:  Login Page is not displayed expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:568)
at com.r1v2.reporting.test.HomePageScenario.testSC_9(HomePageScenario.java:108)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- testSC_9 -->
</testsuite> <!-- com.r1v2.reporting.test.HomePageScenario -->
